// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9FaxjcJyM9UU6sT-835mcB2bYxvAjlqE',
    appId: '1:981616933284:web:cebd194cbbbe004e3fe931',
    messagingSenderId: '981616933284',
    projectId: 'ndp-sushi-restaurant',
    authDomain: 'ndp-sushi-restaurant.firebaseapp.com',
    databaseURL: 'https://ndp-sushi-restaurant-default-rtdb.firebaseio.com',
    storageBucket: 'ndp-sushi-restaurant.appspot.com',
    measurementId: 'G-FT0RWC1BLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWm8gQiPwjj4FvtcllryRQffUVOqaQ1tU',
    appId: '1:981616933284:android:e612c471b27a57df3fe931',
    messagingSenderId: '981616933284',
    projectId: 'ndp-sushi-restaurant',
    databaseURL: 'https://ndp-sushi-restaurant-default-rtdb.firebaseio.com',
    storageBucket: 'ndp-sushi-restaurant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_-PlQZf0vyY2mH7KqUi3W-DLDNnswmyE',
    appId: '1:981616933284:ios:1a536b86fcec2f4e3fe931',
    messagingSenderId: '981616933284',
    projectId: 'ndp-sushi-restaurant',
    databaseURL: 'https://ndp-sushi-restaurant-default-rtdb.firebaseio.com',
    storageBucket: 'ndp-sushi-restaurant.appspot.com',
    iosBundleId: 'com.example.ndpSushiRestaurant',
  );
}
